export const AuthorizationActionTypes = {
  POST_LOGIN_WITH_MOBILE_NUMBER_SUCCESS: 'POST_LOGIN_WITH_MOBILE_NUMBER_SUCCESS',
  POST_LOGIN_NEW_NUMBER_REGISTERED: 'POST_LOGIN_NEW_NUMBER_REGISTERED',
  POST_LOGIN_WITH_MOBILE_NUMBER_FAILURE: 'POST_LOGIN_WITH_MOBILE_NUMBER_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  OTP_LOGIN_SUCCESS: 'OTP_LOGIN_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  OTP_RESENT: 'OTP_RESENT',
  CLEAR_AUTH_STORE: 'CLEAR_AUTH_STORE',
  CLEAR_OTP_STATUS: 'CLEAR_OTP_STATUS',
  POST_LOGIN_NEW_NUMBER_REGISTERED_WITH_MESSAGE: 'POST_LOGIN_NEW_NUMBER_REGISTERED_WITH_MESSAGE',
  POST_SIGNUP_NEW_NUMBER_REGISTERED_WITH_MESSAGE: 'POST_SIGNUP_NEW_NUMBER_REGISTERED_WITH_MESSAGE',
  CLEAR_SIGNUP_WITH_LOGIN_POPUP: 'CLEAR_SIGNUP_WITH_LOGIN_POPUP',
  CLEAR_LOGIN_WITH_SIGNUP_POPUP: 'CLEAR_LOGIN_WITH_SIGNUP_POPUP',
  SET_ERROR_STATUS: 'SET_ERROR_STATUS'
}
