export const ChatActionTypes = {
    CREATE_NEW_CHAT_REQUEST: 'CREATE_NEW_CHAT_REQUEST',
    UPDATE_CHAT_CONVERSATIONS: 'UPDATE_CHAT_CONVERSATIONS',
    UPDATE_MESSAGES: 'UPDATE_MESSAGES',
    CLEAR_MESSAGE_LIST: 'CLEAR_MESSAGE_LIST',
    SET_CURRENT_CONVERSATION: 'SET_CURRENT_CONVERSATION',
    CLEAR_NEW_CHAT: 'CLEAR_NEW_CHAT'
}
