export const UserActionTypes = {
  FETCH_USER_DATA: 'FETCH_USER_DATA',
  DELETE_USER: 'DELETE_USER',
  UPDATE_SELLER_PROFILE: 'UPDATE_SELLER_PROFILE',
  NEW_TICKET_ADDED: 'NEW_TICKET_ADDED',
  CLEAR_SESSION: 'CLEAR_SESSION',
  UPDATE_LOADER_STATUS: 'UPDATE_LOADER_STATUS',
  CLEAR_SELLER_PROFILE: 'CLEAR_SELLER_PROFILE',
  FETCH_ALL_TICKETS: 'FETCH_ALL_TICKETS',
  PRODUCT_TO_BE_EDITED: 'PRODUCT_TO_BE_EDITED',
  CLEAR_SELECTED_ITEM: 'CLEAR_SELECTED_ITEM',
  SET_ERROR_FOR_POPUP: 'SET_ERROR_FOR_POPUP',
  CLEAR_ERROR_FOR_POPUP: 'CLEAR_ERROR_FOR_POPUP'
}
