export const RefDataActionTypes = {
  FETCH_SPONSORSHIP_OPTIONS: 'FETCH_SPONSORSHIP_OPTIONS',
  FETCH_SELL_CATEGORY_DATA: 'FETCH_SELL_CATEGORY_DATA',
  FETCH_RENT_CATEGORY_DATA: 'FETCH_RENT_CATEGORY_DATA',
  FETCH_WANTED_CATEGORY_DATA: 'FETCH_WANTED_CATEGORY_DATA'
}
