export { LaunchWidget } from "./launch-widget/LaunchWidget";
export { LoginWidget } from "./login-widget/LoginWidget";
export { PasswordWidget } from "./password-widget/Password.widget";
export { SignupWidget } from "./signup-widget/Signup.widget";
export { OtpWidget } from "./otp-widget/Otp.widget";
export { ChangePasswordWidget } from "./change-password-widget/ChangePassword.widget";
export { RegisterUserWidget } from "./register-user-widget/RegisterUser.widget";
export { HomeWidget } from "./godhan-home-widget/MainHomeWidget";
export { MainSearchWidget } from "./godhan-search-widget/MainSearchWidget";
export { MainProductWidget } from "./godhan-product-widget/MainProductWidget";
export { MainProfileWidget } from "./godhan-profile-widget/MainProfileWidget";
export { MainNotificationWidget } from "./notifications-widget/MainNotificationWidget";
export { MainCreateCattleAdWidget } from "./godhan-create-cattle-ad-widget/MainCreateCattleAdWidget";
export { MainLocationPage } from "./location-page/MainLocationPage";
export { MainContactWidget } from './godhan-contact-us-widget/MainContactWidget'