export const ItemActionTypes = {
  FETCH_ITEM_LIST: 'FETCH_ITEM_LIST',
  FETCH_ITEMS: 'FETCH_ITEMS',
  UPDATE_COUNTRY_LIST: 'UPDATE_COUNTRY_LIST',
  UPDATE_STATE_LIST: 'UPDATE_STATE_LIST',
  UPDATE_CITY_LIST: 'UPDATE_CITY_LIST',
  ADD_NEW_LIST: 'ADD_NEW_LIST',
  UPDATE_ITEM_LIST: 'UPDATE_ITEM_LIST',
  CREATE_PRODUCT_ID: 'CREATE_PRODUCT_ID',
  PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
  FETCH_HOT_CATEGORIES: 'FETCH_HOT_CATEGORIES',
  FETCH_WANTED_ITEMS: 'FETCH_WANTED_ITEMS',
  CLEAR_NEW_PRODUCT: 'CLEAR_NEW_PRODUCT',
  UPDATE_FILTER_OPTIONS: 'UPDATE_FILTER_OPTIONS',
  UPDATE_FAVOURITE_ITEM_ID: 'UPDATE_FAVOURITE_ITEM_ID',
  UPDATE_WANTED_STATUS: 'UPDATE_WANTED_STATUS',
  CLEAR_PRODUCT_LIST: 'CLEAR_PRODUCT_LIST'
}
